name: maps_app
description: Flutter training project for managing charging stations with maps

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  dio: ^5.0.1
  connectivity_plus: ^3.0.3
  logging: ^1.1.1
  flutter_secure_storage: ^8.0.0
  equatable: ^2.0.5
  stream_transform: ^2.1.0
  go_router: ^6.2.0
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  url_strategy: ^0.2.0
  hive: 
  hive_flutter: 
  google_fonts: ^4.0.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  bloc_test: ^9.1.1
  mockito: ^5.3.2
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+6
  retrofit: ^4.0.1
  fpdart: ^0.5.0
  get_it: ^7.2.0
  collection: ^1.17.0
  flutter_svg: ^2.0.2
  widgets_to_image: ^0.0.2
  google_maps_cluster_manager: ^3.0.0+1
  share_plus: ^6.3.1
  image_picker: ^0.8.7
  geolocator: ^9.0.2
  google_sign_in: ^6.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  retrofit_generator: ^5.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  hive_generator: 

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/bottom_nav_bar/
    - assets/images/map_actions/
    - assets/images/map_types/
    - assets/images/station_details/
    - assets/images/charging/
    - assets/images/app_bar/
    - assets/images/search/
    - assets/images/profile/
    - assets/images/favourites/
    - assets/i18n/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true 