// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ZeSiSnJDkn32L1Ty_pkyjESkBDvbQfg',
    appId: '1:499519537662:web:9183304cb4eda887f400af',
    messagingSenderId: '499519537662',
    projectId: 'maps-app-5d8d8',
    authDomain: 'maps-app-5d8d8.firebaseapp.com',
    storageBucket: 'maps-app-5d8d8.appspot.com',
    measurementId: 'G-0GGYSC14Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3d1Vic-mHrKZ_YCUAxXIFbHlxKj3nQiw',
    appId: '1:499519537662:android:d20b618bcf98e888f400af',
    messagingSenderId: '499519537662',
    projectId: 'maps-app-5d8d8',
    storageBucket: 'maps-app-5d8d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn46WpVKpgBgmQHKNZnGs1THcsaVQr1n8',
    appId: '1:499519537662:ios:c7e020ac14744f9df400af',
    messagingSenderId: '499519537662',
    projectId: 'maps-app-5d8d8',
    storageBucket: 'maps-app-5d8d8.appspot.com',
    iosClientId: '499519537662-3j0384aiapeeb8kp1ckg5kkl22fos0iu.apps.googleusercontent.com',
    iosBundleId: 'tsurkan.maps.app',
  );
}
